/**
 * Phase 10 — PDF generation service.
 *
 * Uses pdfkit to generate PDFs for task summaries and project reports.
 * Returns Buffer for storage in S3/MinIO.
 */
import PDFDocument from "pdfkit";
import { prisma } from "../../config/prisma.js";

export interface PDFGenerateParams {
  title: string;
  content: string;
  fileName: string;
  metadata?: { author?: string; subject?: string };
}

export async function generatePDF(params: PDFGenerateParams): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
    });

    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Title
    doc.fontSize(20).font("Helvetica-Bold").text(params.title, { underline: true });
    doc.moveDown();

    // Metadata
    if (params.metadata?.author) {
      doc.fontSize(10).fill("#666666").text(`Author: ${params.metadata.author}`);
    }
    doc.moveDown();

    // Content
    doc.fontSize(12).font("Helvetica").text(params.content, {
      align: "left",
      lineGap: 4,
    });

    // Footer
    doc.fontSize(10).fill("#999999").text(
      `Generated by Sentient • ${new Date().toLocaleDateString()}`,
      { align: "center" },
    );

    doc.end();
  });
}

export async function generateTaskSummaryPDF(taskId: string): Promise<Buffer> {
  const task = await prisma.task.findFirst({
    where: { id: taskId },
    include: { assignee: true, project: true, comments: { take: 10 } },
  });

  if (!task) throw new Error(`Task not found: ${taskId}`);

  const content = `
Task: ${task.title}
Status: ${task.status}
Priority: ${task.priority}
Assigned to: ${task.assignee?.name ?? "Unassigned"}
Project: ${task.project?.name ?? "N/A"}
Due Date: ${task.dueDate ? new Date(task.dueDate).toLocaleDateString() : "No due date"}

Description:
${task.description ?? "N/A"}

Comments:
${task.comments.map((c: { content: string }) => `- ${c.content}`).join("\n")}
  `.trim();

  return generatePDF({
    title: "Task Summary",
    content,
    fileName: `task-${taskId}.pdf`,
  });
}

export async function generateProjectReportPDF(projectId: string): Promise<Buffer> {
  const project = await prisma.project.findFirst({
    where: { id: projectId },
    include: {
      tasks: {
        where: { deletedAt: null },
      },
    },
  });

  if (!project) throw new Error(`Project not found: ${projectId}`);

  const tasksByStatus = {
    todo: project.tasks.filter((t: { status: string }) => t.status === "todo").length,
    in_progress: project.tasks.filter((t: { status: string }) => t.status === "in_progress").length,
    blocked: project.tasks.filter((t: { status: string }) => t.status === "blocked").length,
    done: project.tasks.filter((t: { status: string }) => t.status === "done").length,
  };

  const completionRate =
    project.tasks.length > 0
      ? Math.round((tasksByStatus.done / project.tasks.length) * 100)
      : 0;

  const content = `
Project Report: ${project.name}
Generated: ${new Date().toLocaleDateString()}

Total Tasks: ${project.tasks.length}
- To Do: ${tasksByStatus.todo}
- In Progress: ${tasksByStatus.in_progress}
- Blocked: ${tasksByStatus.blocked}
- Completed: ${tasksByStatus.done}

Completion Rate: ${completionRate}%
  `.trim();

  return generatePDF({
    title: "Project Report",
    content,
    fileName: `project-${projectId}.pdf`,
  });
}
