/**
 * Email Service Usage Examples
 * 
 * This file demonstrates how to use the EmailService in the authentication system.
 * These examples show integration points for the auth service.
 */

import { emailService } from './email.service.js';

/**
 * Example 1: Send verification email after user registration
 * 
 * This should be called in the auth service after creating a new user.
 */
export async function exampleSendVerificationEmail() {
  const user = {
    email: 'newuser@example.com',
    name: 'John Doe',
  };
  
  const verificationToken = 'generated-verification-token-123'; // Generated by auth service
  
  try {
    await emailService.sendVerificationEmail(
      user.email,
      verificationToken,
      user.name
    );
    console.log('Verification email sent successfully');
  } catch (error) {
    // Email service handles errors gracefully - this won't throw
    // But you can log for monitoring purposes
    console.log('Email service completed (check logs for details)');
  }
}

/**
 * Example 2: Send password reset email
 * 
 * This should be called in the forgot-password endpoint.
 */
export async function exampleSendPasswordResetEmail() {
  const user = {
    email: 'user@example.com',
    name: 'Jane Smith',
  };
  
  const resetToken = 'generated-reset-token-456'; // Generated by auth service
  
  await emailService.sendPasswordResetEmail(
    user.email,
    resetToken,
    user.name
  );
  
  console.log('Password reset email sent');
}

/**
 * Example 3: Send welcome email after email verification
 * 
 * This should be called after successful email verification.
 */
export async function exampleSendWelcomeEmail() {
  const user = {
    email: 'verified@example.com',
    name: 'Alice Johnson',
  };
  
  await emailService.sendWelcomeEmail(
    user.email,
    user.name
  );
  
  console.log('Welcome email sent');
}

/**
 * Example 4: Integration in auth service registration flow
 * 
 * This shows how the email service fits into the complete registration flow.
 */
export async function exampleRegistrationFlow() {
  // 1. Validate input (done by auth service)
  const input = {
    name: 'New User',
    email: 'newuser@example.com',
    password: 'SecurePass123!',
  };
  
  // 2. Create user in database (done by auth service)
  const user = {
    id: 'user-uuid',
    name: input.name,
    email: input.email,
    emailVerified: false,
  };
  
  // 3. Generate verification token (done by auth service)
  const verificationToken = 'random-token-generated-by-crypto';
  const hashedToken = 'bcrypt-hashed-token'; // Stored in database
  
  // 4. Send verification email (using email service)
  await emailService.sendVerificationEmail(
    user.email,
    verificationToken, // Send unhashed token in email
    user.name
  );
  
  // 5. Return response to client
  console.log('User registered successfully, verification email sent');
}

/**
 * Example 5: Development mode behavior
 * 
 * When RESEND_API_KEY is not set or NODE_ENV is 'development' or 'test',
 * emails are logged to console instead of being sent via Resend.
 */
export async function exampleDevelopmentMode() {
  // In development, this will log to console:
  // === EMAIL (Development Mode) ===
  // From: noreply@sentient.dev
  // To: dev@example.com
  // Subject: Verify your email address
  // ... (full email content)
  
  await emailService.sendVerificationEmail(
    'dev@example.com',
    'dev-token',
    'Developer'
  );
}

/**
 * Example 6: Error handling
 * 
 * The email service handles errors gracefully without throwing.
 * This ensures that email failures don't block user registration.
 */
export async function exampleErrorHandling() {
  // Even if Resend API fails, this won't throw an error
  // The error will be logged to console.error
  // User registration can proceed successfully
  
  await emailService.sendVerificationEmail(
    'user@example.com',
    'token',
    'User'
  );
  
  // This code will always execute, even if email sending fails
  console.log('Registration completed successfully');
}
